-- load plugin configuration files here
require("user.core.themes")
require("user.core.autopairs")
require("user.core.comment")
require("user.core.bufferline")
require("user.core.nvim-tree")
require("user.core.lualine")
require("user.core.fterm")
require("user.core.indentline")
require("user.core.telescope")
require("user.core.project")
require("user.core.treesitter")
require("user.core.completions")
require("user.core.illuminate")
require("user.core.lsp")
